from picture import Picture
welcome = Picture('welcome1.png')
background = Picture('background.jpg')
gameBackground = Picture('game-background5.png')
youWinBackground = Picture('you-win.png')
button = Picture('button.png')
mario = Picture('mario1.png')
luigi = Picture('luigi1.png')
scoreOverlay = Picture('scoreOverlay1.png')

icon0 = Picture('blue-shell.png')
icon1 = Picture('red-shell.png')
icon2 = Picture('green-shell.png')
icon3 = Picture('y-star.png')
icon4 = Picture('r-shroom.png')
icon5 = Picture('g-shroom.png')
icon0Click = Picture('blue-shell-box.png')
icon1Click = Picture('red-shell-box.png')
icon2Click = Picture('green-shell-box.png')
icon3Click = Picture('y-star-box.png')
icon4Click = Picture('r-shroom-box.png')
icon5Click = Picture('g-shroom-box.png')
icon6 = Picture('empty.png')
